### ISSUE TITLE
Implement tap tracing support

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#87]
# Implementation

## Implementation details.

Once https://github.com/calyptia/cloud/issues/501 and https://github.com/calyptia/core/issues/184 gets 
ready. We need to implement the corresponding CLI bindings for the API.

## Implementation details.

- Create/Delete/Update trace_session (with parametrised plugins, duration, etc).
- Get trace_session, connects to the SSE streams and pulls the trace records from the API server.
- Get trace_session, allows to subscribe or to read an specific amount (--limit) of records and exit.

### Tasks

- [ ] cli: Implement the create trace_session
- [ ] cloud-e2e: Implement a create trace_session test.
- [ ] cloud-docs: Implement a create trace_session section.
- [ ] cli: Implement the delete trace_session
- [ ] cloud-e2e: Implement a delete trace_session test.
- [ ] cloud-docs: Document the delete trace_session 
- [ ] cli: Implement the update trace_session 
- [ ] cloud-e2e: Implement a update trace_session test
- [ ] cloud-docs: Document the update trace_session section

**Comment by niedbalski** [comment]
Moved to next milestone, hopefully targeting next week.

**Comment by niedbalski** [comment]
@nicolasparada FYI, targeting 0.29.0 release for this.

**Comment by niedbalski** [comment]
@nicolasparada 

Notes on CLI for tap
========================

1. Tap should provide a command to create a trace session for a given pipeline name/id.
    1. This has to be parametrised according to https://github.com/calyptia/api/blob/main/types/trace.go#L9 (input, plugins (—all-plugins or a —plugin multi var), and lifespan in duration format)
    2. Delete/List/Get/Update a session
    3. Post a session
2. Tap session records can be consumed from the CLI
    1. Session records can be read from the CLI in two ways:
        1. “Realtime” —tail (or similar)
        2. Historical records —all and —limit (or similar).
    2. For both cases, the output should:
        1. Imitate t-shartk or similar output stream record format (Id, timestamp, actual record in json)
        2. Allow —pretty-print (pretty print the JSON in structured format).
    3. For both cases fields should be able to be filtered:
        1. —fields=ts,record (?)

**Comment by nicolasparada** [comment]
About 2.iii... Is that really a filter or just a UI column toggle?
If it would be a filter, then it should mean some work on the back-end service to receive a filter param.
